language: java
sudo: false
install: true

addons:
    sonarcloud:
        organization: "jslsolucoes-github"
        branches:
            - develop
            - master
        token:
            secure: "15W7WxYtWLtmLVVcFU0z6TLjImKbcYT/PuAW3J5f5ziMW59GejudBeXsnv1WIeXJuslbdkajQcwaxlCcmeScnVNfTR0gscSCKWo+FJIaXfuzHApG3jkzfe+9dtZLUYp76MccSSySn+9xoXREld3FpgvralnBR66irc+5YzoJV9VZyZBfpvZ/VBcK/S6B13z4Iew97IQ+ZIFsXYIXKBrHlvhc96MwNexkzO8hRUDHiFtGf+H50zJfX7GELTnQyIMo56wSIosLWWVxxtFGBFa16sns+RPJbep4a5JufyOFunzMxQo2JMDU524c+RPOhZZGji890wudFML0kxbac/S27qFTqE2D2W/yAxArKVx4gDBP7ujyaz9ZWruncT/VG9narnychzzskfZ+mC+4MpYpI5IGwKeD+8jlXwY7M1b9itnA+XseQ1ocpXkJEa3v1fVtABvtMaHWABXe7ojUG4CYLWKM/+VYO9sVIjSkiIMDhRrIow9DWr6nWfjBno/yYQz7rG1D0OhC5GlzCss7NV4R5klVlqIs7cCehxpn2YXp3ySvH6rmosW2XNwN3+isj0JqNNumriOOQBc9EvYwUrHf1HfdxtHhAuYFejZxLrYy++ySuVJYQszaCDeOfkDeglgTOcWvmFPvt2G2QgTFwhn6FyA1xmARBfPOlx8MXEm9mUs="

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -DskipTests

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'




